import typography from '@tailwindcss/typography'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#563400',
        'on-secondary-fixed-variant': '#006947',
        'surface-container-high': '#e1e9ee',
        'on-primary-fixed': '#373f54',
        'on-secondary-fixed': '#004930',
        'inverse-primary': '#dae2fd',
        secondary: '#006d4a',
        'on-secondary-container': '#005e3f',
        'on-tertiary': '#fff7f3',
        'tertiary-fixed-dim': '#e79400',
        'on-primary': '#f7f7ff',
        'inverse-surface': '#0b0f10',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#cfdce3',
        primary: '#565e74',
        tertiary: '#865400',
        'surface-container-highest': '#d9e4ea',
        'primary-fixed': '#dae2fd',
        'error-container': '#fe8983',
        'surface-tint': '#565e74',
        outline: '#717c82',
        'primary-container': '#dae2fd',
        'surface-container-low': '#f0f4f7',
        'error-dim': '#4e0309',
        'on-surface-variant': '#566166',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d9e4ea',
        'on-error': '#fff7f6',
        'secondary-fixed-dim': '#5fedb0',
        'secondary-dim': '#005f40',
        'secondary-fixed': '#6ffbbe',
        error: '#9f403d',
        'outline-variant': '#a9b4b9',
        'tertiary-dim': '#764900',
        surface: '#f7f9fb',
        background: '#f7f9fb',
        'primary-dim': '#4a5268',
        'on-background': '#2a3439',
        'on-surface': '#2a3439',
        'on-error-container': '#752121',
        'on-tertiary-fixed': '#2a1700',
        'tertiary-fixed': '#f8a010',
        'tertiary-container': '#f8a010',
        'on-tertiary-container': '#4a2c00',
        'on-primary-fixed-variant': '#535b71',
        'secondary-container': '#6ffbbe',
        'inverse-on-surface': '#9a9d9f',
        'on-primary-container': '#4a5167',
        'surface-container': '#e8eff3',
        'on-secondary': '#e6ffee',
        'primary-fixed-dim': '#ccd4ee',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        manrope: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [typography],
}
